### PR TITLE
Tweaks to allow finding Magpie Adapter from setup install

### PR DESCRIPTION
**Pull request by fmigneault**
for PR Ouranosinc/Magpie#82

### CODE REVIEW

**Review by dbyrns — COMMENTED** [review]
Is it working properly now?
I would gladly approve it if it is.

**Comment by fmigneault** [comment]
@dbyrns 
With the latest commit, seems to work locally
Haven't updated it on the remote yet.

**Review by dbyrns — COMMENTED** [review]
I don't see why this is required since allowed_content_types is only use in the section where service_type is a wps... (comment related to commit 340bb13)

**Comment by fmigneault** [comment]
@dbyrns 
When I was running the route: 
https://colibri.crim.ca/twitcher/ows/proxy/thredds/catalog.html

The returned html was refused somehow.
Maybe it was caused by invalid adapter loaded though.
We could revert it and see if it is indeed unnecessary.

**Comment by dbyrns** [comment]
We will wait for the patch in magpie adapter fetch_by_name fct in MagpieServiceStore and then it's fine.
Working perfectly for WPS services.

**Pull request merged**
